const FIXED = "FIXED";
const BLOCK = "BLOCK";
const OPEN_SEARCH = "OPEN_SEARCH";
const CLOSE_SEARCH = "CLOSE_SEARCH";
const REQUEST_SEARCH = "REQUEST_SEARCH";
const FETCHED_SEARCH = "FETCHED_SEARCH";
const FAILED_SEARCH = "FAILED_SEARCH";
const CHNAGE_VALUE_SEARCH = "CHNAGE_VALUE_SEARCH";
const RESET_VALUE_SEARCH = "RESET_VALUE_SEARCH";

export {
  FIXED,
  BLOCK,
  OPEN_SEARCH,
  CLOSE_SEARCH,
  REQUEST_SEARCH,
  FETCHED_SEARCH,
  FAILED_SEARCH,
  CHNAGE_VALUE_SEARCH,
  RESET_VALUE_SEARCH,
};
