const FIXED = "FIXED";
const BLOCK = "BLOCK";
const OPEN_SEARCH = "OPEN_SEARCH";
const CLOSE_SEARCH = "CLOSE_SEARCH";
const CHANGE_TEXT = "CHANGE_TEXT";

export { FIXED, BLOCK, OPEN_SEARCH, CHANGE_TEXT, CLOSE_SEARCH };
